image: gitpod/workspace-full-vnc

ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y android-sdk
      echo "Android SDK installed"
